version: "3.8"
services:
  chat-api:
    build:
      args:
        GO_BUILD_EXTRA_FLAGS: " -race "
        CGO_ENABLED: 1
    environment:
      SERVICE_MODE: "test"

  pg:
    ports:
      - 5432:5432
  pwmanager:
